#!/usr/bin/python3

import sys

def factorize(n):
    """
    Factorize a given number n into a product of two smaller numbers.
    """
    for i in range(2, int(n**0.5)+1):
        if n % i == 0:
            return (i, n//i)
    return (n, 1)

def main():
    """
    Read the input file, factorize each number, and print the result.
    """
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        return
    try:
        with open(sys.argv[1], 'r') as f:
            for line in f:
                n = int(line.strip())
                p, q = factorize(n)
                print("{}={}*{}".format(n, p, q))
    except IOError:
        print("File not found")

if __name__ == '__main__':
    main()

