#!/usr/bin/python3
import sys

def is_prime(n):
    """
    Check if a given number n is prime.
    """
    if n < 2:
        return False
    for i in range(2, int(n**0.5)+1):
        if n % i == 0:
            return False
    return True

def factorize(n):
    """
    Factorize a given number n into a product of two prime numbers.
    """
    if n < 2:
        return None
    for i in range(2, int(n**0.5)+1):
        if n % i == 0 and is_prime(i) and is_prime(n//i):
            return i, n//i
    return None

if __name__ == '__main__':
    with open(sys.argv[1], "r") as fp:
        n = int(fp.readline().strip())
        factors = factorize(n)
        if factors:
            print("{}={}*{}".format(n, factors[0], factors[1]))
        else:
            print("Unable to factorize {} into two primes.".format(n))

